version: '3'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: web-server
    ports:
      - "3000:3000"
    env_file:
      - server/.env.prod
    volumes:
      - ./server:/app/server